version: '3.4'

services:
  condotech:
    image: ${DOCKER_REGISTRY-}condotech
    build:
      context: .
      dockerfile: CondoTech/Dockerfile
  db:
      build: ./mysql/
      environment:
        - MYSQL_ROOT_PASSWORD=root_pwd
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=pa55word
      ports:
        - "3306:3306"
      volumes:
        - mysqldata:/var/lib/mysql

volumes:
  mysqldata: 

